### ISSUE TITLE
Fix: use correct syntax for environment variable

### ISSUE THREAD

**Issue by jorianvo** [jorianvo/vue-ci#40]
I can't find the proper documentation on how to access an environment variable outside of shell context i.e. a `run` step. But [this](https://github.community/t/env-interpolation-within-actions/120196/2) seems the way to do it:

```yaml
      - uses: docker/build-push-action@v1 # https://github.com/marketplace/actions/build-and-push-docker-images
        with:
          username: $GITHUB_ACTOR
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{env.INPUT_REPOSITORY}}
          tags: latest
```
